import './globals.css';
import { Inter } from 'next/font/google';
import ShopProvider from '@/context/shopContext';
import Layout from '@/components/Layout';

// // import function to register Swiper custom elements
// import { register } from 'swiper/element/bundle';
// // register Swiper custom elements
// register();

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ShopProvider>
					<Layout>{children}</Layout>
				</ShopProvider>
			</body>
		</html>
	);
}
